// Function to render the license badge
function renderLicenseBadge(license) {
  let yourLicense = '';

  if (license === 'MIT') {
    yourLicense = '![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)';
  } else if (license === 'GPLv3') {
    yourLicense = '![GPLv3 license](https://img.shields.io/badge/License-GPLv3-blue.svg)';
  } else if (license === 'GPL') {
    yourLicense = '![GPL license](https://img.shields.io/badge/License-GPL-blue.svg)';
  } else {
    yourLicense = 'N/A';
  }

  return yourLicense;
}

function generateMarkdown(data) {
  // License badge is generated by invoking renderLicenseBadge function with the license data
  const licenseBadge = renderLicenseBadge(data.license);

  // Return the Markdown content with the license badge included
  return `# ${data.title}

${licenseBadge}

## Description
${data.description}

## Table of Contents
- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)

## Installation
${data.installation}

## Usage
${data.usage}

## Contributing
${data.contributing}

## Tests
${data.tests}

## Questions
For any questions, please contact ${data.author} at ${data.email}.
`;
}

module.exports = generateMarkdown;
